POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0ODAzOWFjZGE0YTdlZmMyNjAxNTA4MyIsImlhdCI6MTY4NjIwMjAxM30.W9rYWqy0xWPmg55Isi7DTWJR1pFVUXS0ncBB64mPgeU

{
    "content": "Testing with Authorization 2",
    "important": true,
    "userId": "64c4a1c815eb99c51c962578"
}

###
GET  http://localhost:3001/api/notes

###
DELETE  http://localhost:3001/api/notes/648230c4431d868d8a889774

###
PUT  http://localhost:3001/api/notes/64c4a35a15eb99c51c962584
Content-Type: application/json

{
    "content": "Postman is a good tool for backend testing",
    "important": true
}