POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Testing with user",
    "important": true,
    "userId": "648039acda4a7efc26015083"
}

###
GET  http://localhost:3001/api/notes

###
DELETE  http://localhost:3001/api/notes/6456a0581b65702a48342944

###
PUT  http://localhost:3001/api/notes/6455fbca119382ba1b528236
Content-Type: application/json

{
    "content": "Postman is a good tool for backend testing",
    "important": true
}